# This file tells Streamlit Cloud how to set up and run your app

[server]
headless = true

[theme]
primaryColor = "#1DB954"
backgroundColor = "#191414"
secondaryBackgroundColor = "#282828"
textColor = "#FFFFFF"

[runner]
magicEnabled = true

[client]
showSidebarNavigation = true
